version: "3.9"
services:
  postgres:
    image: postgres:13-alpine
    container_name: analysis-db
    environment:
      - POSTGRES_DB=${TYPEORM_DATABASE}
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
    ports: 
      - '${TYPEORM_PORT}:5432'
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: analysis-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGA_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGA_PASSWORD}
    ports: 
      - '${PGA_PORT}:80'
    restart: unless-stopped
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  postgres:
  pgadmin:
