version: "2"
services:
  nest:
    build: .
    container_name: nest
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
      - .env:/app/.env

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: analysis-nginx
    depends_on:
      - nest
    environment:
      - NGINX_SERVER_NAME=localhost
      - NEST_HOST=nest
      - NEST_PORT=3000
      - NGINX_MAX_BODY=100M
    ports:
      - 80:80

  postgres:
    image: postgres:13
    container_name: analysis-db
    environment:
      - POSTGRES_DB=analysis_db
      - POSTGRES_USER=analysisuser
      - POSTGRES_PASSWORD=analysis-test
    ports: 
      - '5432:5432'
    restart: unless-stopped
    volumes: 
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: analysis-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@.test.mx
      - PGADMIN_DEFAULT_PASSWORD=root
    ports: 
      - '5050:80'
    restart: unless-stopped
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  postgres:
  pgadmin:
